### ISSUE TITLE
Unexpected error loading module: /config/apps/growatt_app.py

### ISSUE THREAD

**Issue by RienduPre** [tkupka/ad-growatt#1]
Hi,

I started to use your setup, but get this error in the appdeamon log.
Any help is more than welcome.

Core=2024.3.1
Supervisor=2024.03.0
Operating System=12.1
Frontend=20240307.0
AppDeamon=0.16.4

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.16.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.1  (aarch64 / odroid-n2)
 Home Assistant Core: 2024.3.1
 Home Assistant Supervisor: 2024.03.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[12:33:38] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2024-03-17 12:33:42.517115 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-03-17 12:33:42.517568 INFO AppDaemon: Python version is 3.11.6
2024-03-17 12:33:42.517838 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-03-17 12:33:42.518110 INFO AppDaemon: Added log: AppDaemon
2024-03-17 12:33:42.518442 INFO AppDaemon: Added log: Error
2024-03-17 12:33:42.518679 INFO AppDaemon: Added log: Access
2024-03-17 12:33:42.519012 INFO AppDaemon: Added log: Diag
2024-03-17 12:33:42.767689 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-03-17 12:33:43.016357 INFO HASS: HASS Plugin Initializing
2024-03-17 12:33:43.016592 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-03-17 12:33:43.016774 INFO HASS: HASS Plugin initialization complete
2024-03-17 12:33:43.017239 INFO AppDaemon: Initializing HTTP
2024-03-17 12:33:43.017591 INFO AppDaemon: Using 'socketio' for event stream
2024-03-17 12:33:43.024656 INFO AppDaemon: Starting API
2024-03-17 12:33:43.027289 INFO AppDaemon: Starting Admin Interface
2024-03-17 12:33:43.027740 INFO AppDaemon: Starting Dashboards
2024-03-17 12:33:43.046260 INFO HASS: Connected to Home Assistant 2024.3.1
2024-03-17 12:33:43.059002 INFO AppDaemon: App 'get_charge_settings' added
2024-03-17 12:33:43.060607 INFO AppDaemon: Found 1 active apps
2024-03-17 12:33:43.060948 INFO AppDaemon: Found 0 inactive apps
2024-03-17 12:33:43.061152 INFO AppDaemon: Found 0 global libraries
2024-03-17 12:33:43.061409 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2024-03-17 12:33:43.062339 INFO AppDaemon: Running on port 5050
2024-03-17 12:33:43.148738 INFO HASS: Evaluating startup conditions
2024-03-17 12:33:43.165513 INFO HASS: Startup condition met: hass state=RUNNING
2024-03-17 12:33:43.165847 INFO HASS: All startup conditions met
2024-03-17 12:33:43.257847 INFO AppDaemon: Got initial state from namespace default
2024-03-17 12:33:45.070411 INFO AppDaemon: Scheduler running in realtime
2024-03-17 12:33:45.072524 INFO AppDaemon: Adding /config/apps to module import path
2024-03-17 12:33:45.075468 INFO AppDaemon: Loading App Module: /config/apps/growatt_app.py
2024-03-17 12:33:45.166782 WARNING Error: ------------------------------------------------------------
2024-03-17 12:33:45.167292 WARNING Error: Unexpected error loading module: /config/apps/growatt_app.py:
2024-03-17 12:33:45.167544 WARNING Error: ------------------------------------------------------------
2024-03-17 12:33:45.171880 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1000, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 783, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/apps/growatt_app.py", line 3, in <module>
    import stateLogger
ModuleNotFoundError: No module named 'stateLogger'

2024-03-17 12:33:45.172220 WARNING Error: ------------------------------------------------------------
2024-03-17 12:33:45.172482 WARNING AppDaemon: Removing associated apps:
2024-03-17 12:33:45.172770 WARNING AppDaemon: get_charge_settings
2024-03-17 12:33:45.174554 WARNING AppDaemon: No app description found for: /config/apps/growattServer.py - ignoring
2024-03-17 12:33:45.175688 INFO AppDaemon: App initialization complete`

**Comment by tkupka** [comment]
I have added the missing file. 
Now it will be working.
